import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NextUIWrapper from './_components/shared/providers/NextUIWrapper';
import Navigation from './_components/shared/Navigation';
import ScrollToTopWrapper from './_components/shared/providers/ScrollToTopWrapper';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Nextjs EmailsLetter App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <NextUIWrapper>
                    <Navigation />
                    <ClerkProvider>
                    {children}
                    </ClerkProvider>
                    <ScrollToTopWrapper />
                </NextUIWrapper>
            </body>
        </html>
    );
}
